/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.drawerlayout;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f040039;
        public static final int font = 0x7f040139;
        public static final int fontProviderAuthority = 0x7f04013c;
        public static final int fontProviderCerts = 0x7f04013d;
        public static final int fontProviderFetchStrategy = 0x7f04013e;
        public static final int fontProviderFetchTimeout = 0x7f04013f;
        public static final int fontProviderPackage = 0x7f040140;
        public static final int fontProviderQuery = 0x7f040141;
        public static final int fontStyle = 0x7f040142;
        public static final int fontVariationSettings = 0x7f040143;
        public static final int fontWeight = 0x7f040144;
        public static final int ttcIndex = 0x7f040310;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f060138;
        public static final int notification_icon_bg_color = 0x7f060139;
        public static final int ripple_material_light = 0x7f0602c8;
        public static final int secondary_text_default_material_light = 0x7f0602eb;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f070088;
        public static final int compat_button_inset_vertical_material = 0x7f070089;
        public static final int compat_button_padding_horizontal_material = 0x7f07008a;
        public static final int compat_button_padding_vertical_material = 0x7f07008b;
        public static final int compat_control_corner_material = 0x7f07008c;
        public static final int compat_notification_large_icon_max_height = 0x7f07008d;
        public static final int compat_notification_large_icon_max_width = 0x7f07008e;
        public static final int notification_action_icon_size = 0x7f07010f;
        public stati